[book]
authors = ["Daniel Noland"]
language = "en"
multilingual = false
src = "."
title = "Hedgehog Dataplane Design Notes"

[build]
build-dir = ".generated-docs"
create-missing = false

#[preprocessor.plantuml]
#plantuml-cmd = "/bin/plantuml"
#renderers = ["html", "markdown"]
#after = ["links"]

[preprocessor.alerts]
renderers = ["html"]

[output.html]
additional-css = []
smart-punctuation = true
preferrred-dark-theme = "ayu"
default-theme = "light"

[output.markdown]
