[workspace]

members = [
	"dpdk",
	"dpdk-sys",
	"dpdk-thin",
	"errno",
	"net",
	"scratch",
]
resolver = "2"

[workspace.dependencies]
bindgen = { version = "0.70" }
bolero = { version = "0.11" }
cc = { version = "1" }
doxygen-rs = { version = "0.4" }
libc = { version = "0.2" }
rstest = { version = "0.22", default-features = false, features = [] }
serde = { version = "1", default-features = false, features = ["derive", "alloc", "rc"] }
syscalls = { version = "0.6" }
thiserror = { version = "2", package = "thiserror-no-std" } # replace with regular thiserror when https://github.com/dtolnay/thiserror/pull/304 lands
tracing = { version = "0.1", default-features = false, features = ["attributes"] }
tracing-subscriber = { version = "0.3" }
tracing-test = { version = "0.2" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
overflow-checks = false
#split-debuginfo = "packed"
strip = "none"
# NOTE: I expect that we will use objcopy / strip to keep the debug symbols in a separate file
# We _could_ just compile without them, but if you need debug symbols for a release build, you
# are already having a rough day, and if you need them and don't have them then you are having a
# worse day :)
#
# That said, debug-assertions should still be false so that compiler optimizations are not
# inhibited.
debug = true
debug-assertions = false

[profile.dev]
opt-level = 0
lto = false
incremental = true
debug = true

[profile.analysis]
inherits = "dev"
codegen-units = 1
lto = "thin"
incremental = false

[profile.fuzz]
inherits = "release"
