[package]
name = "oxy-dpdk"
version = "0.0.1"
edition = "2021"

[features]
default = ["tracing"]
tracing = ["dep:tracing"]

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true, optional = true, features = ["attributes"] }
tracing-subscriber = { workspace = true }

[build-dependencies]
bindgen = { workspace = true, features = ["runtime"] }
doxygen-rs = { workspace = true }
