[target.x86_64-unknown-linux-gnu]
runner = 'sudo -E'
rustflags = [

		"-C", "linker=clang",
		"-C", "link-arg=-fuse-ld=lld",
		"-C", "link-arg=--ld-path=/usr/bin/ld.lld",

	# Full RELRO as a basic security measure
	# <https://www.redhat.com/en/blog/hardening-elf-binaries-using-relocation-read-only-relro>
		"-C", "relro-level=full",

	#	"-C", "codegen-units=1",
	#	"-C", "linker-plugin-lto",
	#	"-C", "lto=thin",
	#	"-C", "opt-level=3",
	#	"-C", "embed-bitcode=yes",
	#	"-Z", "sanitizer=cfi",
]